import type { UiLanguage } from "@/lib/ui-language";

export const downloadCopy = {
  de: {
    languageLabel: "Sprache wählen",
    home: "Zur Startseite",
    expiredTitle: "Dieser Link ist abgelaufen.",
    expiredBody: "Die Laufzeit dieser Übertragung ist beendet. Bitte die sendende Person um einen neuen Link.",
    missingTitle: "Link nicht gefunden.",
    missingBody: "Prüfe den Link oder bitte die sendende Person, ihn noch einmal zu teilen.",
    sharedKicker: "Für dich freigegeben",
    encryptedKicker: "Für dich verschlüsselt",
    oneFile: "Eine Datei wartet auf dich.",
    multipleFiles: (count: number) => `${count} Dateien warten auf dich.`,
    total: "Gesamt",
    downloadAll: "Alle Dateien herunterladen",
    downloadAllHint: "Gemeinsam als ZIP-Datei",
    downloadFile: (name: string) => `${name} herunterladen`,
    secureDownloadFile: (name: string) => `${name} sicher herunterladen`,
    validUntil: "Dieser Link ist gültig bis",
    encryptedUntil: "Entschlüsselung nur auf deinem Gerät. Gültig bis",
    clockSuffix: "Uhr",
    encryptedBadge: "Ende-zu-Ende verschlüsselt",
    individualFiles: "Die Dateien werden einzeln auf diesem Gerät entschlüsselt.",
    missingKeyTitle: "Schlüssel fehlt oder ist ungültig.",
    decrypting: "Freigabe wird lokal entschlüsselt …",
    invalidMetadata: "Die verschlüsselten Dateiinformationen stimmen nicht mit der Übertragung überein.",
    decryptFailed: "Die Übertragung konnte nicht entschlüsselt werden.",
    streamingUnsupported: "Dieser Browser unterstützt keine sicheren Streaming-Downloads.",
    workerReload: "Download-Dienst konnte nicht gestartet werden. Bitte lade die Seite neu.",
    workerUnavailable: "Download-Dienst ist nicht verfügbar.",
    workerNoResponse: "Download-Dienst antwortet nicht.",
    downloadFailed: "Download fehlgeschlagen.",
    downloadIncomplete: "Der verschlüsselte Download ist unvollständig.",
    downloadStartTimeout: "Der Download konnte nicht gestartet werden. Bitte versuche es erneut.",
    downloadIdleTimeout: "Der Download antwortet nicht mehr. Bitte versuche es erneut.",
    downloadCancelled: "Download wurde abgebrochen.",
    decryptionFailed: "Entschlüsselung fehlgeschlagen.",
    fileDecryptFailed: "Der Download konnte nicht entschlüsselt werden.",
    locale: "de-DE",
  },
  en: {
    languageLabel: "Choose language",
    home: "Back to home",
    expiredTitle: "This link has expired.",
    expiredBody: "This transfer is no longer available. Please ask the sender for a new link.",
    missingTitle: "Link not found.",
    missingBody: "Check the link or ask the sender to share it again.",
    sharedKicker: "Shared with you",
    encryptedKicker: "Encrypted for you",
    oneFile: "One file is waiting for you.",
    multipleFiles: (count: number) => `${count} files are waiting for you.`,
    total: "Total",
    downloadAll: "Download all files",
    downloadAllHint: "Together as a ZIP file",
    downloadFile: (name: string) => `Download ${name}`,
    secureDownloadFile: (name: string) => `Download ${name} securely`,
    validUntil: "This link is valid until",
    encryptedUntil: "Decrypted only on your device. Valid until",
    clockSuffix: "",
    encryptedBadge: "End-to-end encrypted",
    individualFiles: "The files are decrypted individually on this device.",
    missingKeyTitle: "The key is missing or invalid.",
    decrypting: "Decrypting this share locally …",
    invalidMetadata: "The encrypted file information does not match this transfer.",
    decryptFailed: "The transfer could not be decrypted.",
    streamingUnsupported: "This browser does not support secure streaming downloads.",
    workerReload: "The download service could not start. Please reload the page.",
    workerUnavailable: "The download service is unavailable.",
    workerNoResponse: "The download service is not responding.",
    downloadFailed: "Download failed.",
    downloadIncomplete: "The encrypted download is incomplete.",
    downloadStartTimeout: "The download could not start. Please try again.",
    downloadIdleTimeout: "The download stopped responding. Please try again.",
    downloadCancelled: "The download was cancelled.",
    decryptionFailed: "Decryption failed.",
    fileDecryptFailed: "The download could not be decrypted.",
    locale: "en-GB",
  },
} as const satisfies Record<UiLanguage, object>;
