export const uploadTranslations = {
  de: {
    tooManyFiles: (maximum: number) => `Du kannst höchstens ${maximum} Dateien auf einmal teilen.`,
    limits: "max. 20 Dateien · 5\u00a0GB",
    retrying: (attempt: number, maximum: number, seconds: number) => `Verbindung unterbrochen. Neuer Versuch ${attempt}/${maximum} in ${seconds} Sek. …`,
    cancelConfirmation: "Gesamten Upload abbrechen? Bereits übertragene Daten werden nach Möglichkeit sofort gelöscht, andernfalls automatisch bereinigt. Bei einem Fehler bleibt der Upload pausiert, damit du das Löschen erneut versuchen kannst.",
    cancelFailed: "Das sofortige Löschen konnte nicht bestätigt werden. Der Upload bleibt pausiert. Bitte versuche den Abbruch erneut; andernfalls greift die automatische Bereinigung bzw. das Ablaufdatum.",
    cancelCleanupFailed: "Der Upload wurde abgebrochen, aber das sofortige Löschen konnte nicht bestätigt werden. Die Daten werden automatisch bereinigt bzw. nach Ablauf entfernt.",
    tooLarge: "Die Übertragung darf insgesamt höchstens 5 GB groß sein.",
    emptyOrFolder: "Ordner oder leere Dateien können nicht hochgeladen werden. Bitte wähle einzelne Dateien oder packe den Ordner als ZIP-Datei.",
    uploadFailed: "Die Übertragung konnte nicht erstellt werden.",
    connectionLost: "Die Verbindung wurde beim Hochladen unterbrochen.",
    copyManually: "Bitte markiere den Link und kopiere ihn manuell.",
    shareTitle: "Freigabelink",
    ready: "Bereit zum Teilen",
    linkReady: "Dein Link ist fertig.",
    resultCopy: (plural: boolean) => `Jeder mit diesem Link kann die ${plural ? "Dateien" : "Datei"} bis zum Ablaufdatum herunterladen.`,
    openLink: "Freigabelink öffnen",
    copyLink: "Freigabelink kopieren",
    file: "Datei",
    files: "Dateien",
    uploadedFileCount: (completed: number, total: number) => `Dateien ${completed}/${total}`,
    until: "bis",
    linkCopied: "Link kopiert",
    shareLink: "Hochladen & Link erstellen",
    shareAction: "Link teilen",
    newTransfer: "Neue Übertragung erstellen",
    newTransferKicker: "Neue Übertragung",
    question: "Was möchtest du teilen?",
    chooseFiles: "Dateien auswählen",
    dropLabel: "Dateien hier ablegen oder auswählen",
    dropFiles: "Dateien hier ablegen",
    clickToChoose: "oder klicken, um auszuwählen",
    selectedFiles: "Ausgewählte Dateien",
    ofMaximum: "von 5\u00a0GB",
    uploaded: "hochgeladen",
    perSecond: "pro Sekunde",
    remaining: "verbleibend",
    timeRemaining: "Restzeit",
    remove: "entfernen",
    pauseUpload: "Upload pausieren",
    resumeUpload: "Upload fortsetzen",
    validFor: "Link gültig für",
    day: "Tag",
    days: "Tage",
    note: "Notiz",
    optional: "optional",
    placeholder: "z. B. hier sind die Urlaubsfotos …",
    cancelUpload: "Gesamten Upload abbrechen und löschen",
    removeUploadingFile: (name: string) => `${name} aus diesem Upload entfernen`,
    removeFileFailed: "Die Datei konnte nicht aus dem Upload entfernt werden.",
    recoveryTitle: "Unterbrochenen Upload fortsetzen",
    recoveryBody: "Wähle dieselben Dateien erneut aus. Danach läuft der Upload automatisch an der letzten bestätigten Stelle weiter.",
    recoveryChoose: "Dateien erneut auswählen",
    recoveryDiscard: "Upload verwerfen",
    recoveryMismatch: "Die ausgewählten Dateien stimmen nicht mit dem unterbrochenen Upload überein.",
    recoveryUnavailable: "Der unterbrochene Upload ist nicht mehr verfügbar. Bitte starte eine neue Übertragung.",
    privacyTitle: "Datenschutzhinweise",
    imprintTitle: "Impressum",
    termsTitle: "Nutzungsbedingungen",
    termsAcceptanceStart: "Ich akzeptiere die",
    termsAcceptanceMiddle: "und habe die",
    privacyAcknowledgementTitle: "Datenschutzhinweise",
    termsAcceptanceEnd: "zur Kenntnis genommen.",
    locale: "de-DE",
  },
  en: {
    tooManyFiles: (maximum: number) => `You can share up to ${maximum} files at once.`,
    limits: "max. 20 files · 5\u00a0GB",
    retrying: (attempt: number, maximum: number, seconds: number) => `Connection interrupted. Retry ${attempt}/${maximum} in ${seconds} sec …`,
    cancelConfirmation: "Cancel the entire upload? Uploaded data will be deleted immediately where possible, otherwise automatically cleaned up. If deletion fails, the upload stays paused so you can retry deleting it.",
    cancelFailed: "Immediate deletion could not be confirmed. The upload remains paused. Please try cancelling again; otherwise automatic cleanup or the expiry date applies.",
    cancelCleanupFailed: "The upload was cancelled, but immediate deletion could not be confirmed. The data will be cleaned up automatically or removed after expiry.",
    tooLarge: "The transfer may not exceed 5 GB in total.",
    emptyOrFolder: "Folders or empty files cannot be uploaded. Please choose individual files or create a ZIP archive first.",
    uploadFailed: "The transfer could not be created.",
    connectionLost: "The connection was interrupted during upload.",
    copyManually: "Please select the link and copy it manually.",
    shareTitle: "Share link",
    ready: "Ready to share",
    linkReady: "Your link is ready.",
    resultCopy: (plural: boolean) => `Anyone with this link can download the ${plural ? "files" : "file"} until it expires.`,
    openLink: "Open share link",
    copyLink: "Copy share link",
    file: "file",
    files: "files",
    uploadedFileCount: (completed: number, total: number) => `Files ${completed}/${total}`,
    until: "until",
    linkCopied: "Link copied",
    shareLink: "Upload & create link",
    shareAction: "Share link",
    newTransfer: "Create another transfer",
    newTransferKicker: "New transfer",
    question: "What are you sharing?",
    chooseFiles: "Choose files",
    dropLabel: "Drop files here or choose files",
    dropFiles: "Drop files here",
    clickToChoose: "or click to choose",
    selectedFiles: "Selected files",
    ofMaximum: "of 5\u00a0GB",
    uploaded: "uploaded",
    perSecond: "per second",
    remaining: "remaining",
    timeRemaining: "Time remaining",
    remove: "remove",
    pauseUpload: "Pause upload",
    resumeUpload: "Resume upload",
    validFor: "Link valid for",
    day: "day",
    days: "days",
    note: "Note",
    optional: "optional",
    placeholder: "e.g. here are the holiday photos …",
    cancelUpload: "Cancel and delete entire upload",
    removeUploadingFile: (name: string) => `Remove ${name} from this upload`,
    removeFileFailed: "The file could not be removed from the upload.",
    recoveryTitle: "Resume interrupted upload",
    recoveryBody: "Choose the same files again. The upload will automatically continue from the last confirmed position.",
    recoveryChoose: "Choose files again",
    recoveryDiscard: "Discard upload",
    recoveryMismatch: "The selected files do not match the interrupted upload.",
    recoveryUnavailable: "The interrupted upload is no longer available. Please start a new transfer.",
    privacyTitle: "Privacy Notice",
    imprintTitle: "Legal notice",
    termsTitle: "Terms of Use",
    termsAcceptanceStart: "I accept the",
    termsAcceptanceMiddle: "and acknowledge the",
    privacyAcknowledgementTitle: "Privacy Notice",
    termsAcceptanceEnd: ".",
    locale: "en-GB",
  },
} as const;
